### ISSUE TITLE
Introduction to the Theory of Computation 3rd Edition M Sipser, errors

### ISSUE THREAD

**Issue by AyyyCM** [izzybeetschen/pdf-splitting#12]
- does not recognise chapter 0 for first split but starts exactly at chapter 1
- in split 1 and forward it seems to have the chapter in the middle
- This book has parts containing chapters which it won't like I imagine

very impressive though

**Comment by izzybeetschen** [comment]
The chapters starting in the middle I believe was an issue with chapter 6 in which the application was failing to recognise that chapter 6 was a chapter due to bad reading of the PDF. This was fixed with further normalization of content page lines.

Additionally, the textbook page offset from actual page numbers and the page number reported on the page was failing to calculate properly - this may have been the reason for why the PDFs were not at the start of the chapter. Have a go now and see if it works for you. Feel free to open another issue if you find more problems.

Thank you!! :)
